/**
 * Mountain geometry builder.
 *
 * Mountains are 3D raised terrain tiles with sloped sides. Each side draws a
 * flat vertical face AND (if border width > 0) a sloped corner piece.
 * Neighbor-aware: faces adjacent to same-type mountains are hidden.
 *
 * Differences from RPM/THREE.js:
 *   - Babylon.js is left-handed (Z+ = forward), THREE.js is right-handed
 *     (Z+ = toward viewer). We negate rotation angles to compensate.
 *   - Babylon.js texture with invertY=true flips V; we invert V in UVs.
 *   - RPM has no top cap — floor tiles at the mountain position provide the top.
 *
 * Texture is a 4×4 atlas generated by MountainAtlas.ts from a 3×3 source.
 */

import { VertexData } from "@babylonjs/core/Meshes/mesh.vertexData";
import { SQUARE_SIZE, COEF_TEX } from "./Constants";

/** Mountain data from RPM JSON or editor state. */
export interface MountainData {
    /** Special ID referencing the mountain texture. */
    sid: number;
    /** Width in squares (horizontal slope extent). */
    ws: number;
    /** Width sub-pixel percent (0-99). */
    wp: number;
    /** Height in squares (vertical rise). */
    hs: number;
    /** Height sub-pixel percent (0-99). */
    hp: number;
    /** Cardinal neighbor flags — set by update(). */
    t: boolean;  // top (north) neighbor
    b: boolean;  // bottom (south) neighbor
    l: boolean;  // left (west) neighbor
    r: boolean;  // right (east) neighbor
    /** Diagonal neighbor flags — for concave corner detection (pits). */
    tl?: boolean;  // top-left (NW)
    tr?: boolean;  // top-right (NE)
    bl?: boolean;  // bottom-left (SW)
    br?: boolean;  // bottom-right (SE)
    /** Mountain texture source path (each mountain remembers its texture) */
    tex?: string;
    /** If true, mountain goes downward (pit) instead of upward */
    inverted?: boolean;
}

// Texture grid offsets matching RPM's 4×4 mountain atlas layout.
const X_LEFT_OFFSET = 0;
const X_MID_OFFSET = 1;
const X_RIGHT_OFFSET = 2;
const X_MIX_OFFSET = 3;
const Y_TOP_OFFSET = 0;
const Y_MID_OFFSET = 1;
const Y_BOT_OFFSET = 2;
const Y_MIX_OFFSET = 3;

type Vec3 = { x: number; y: number; z: number };

function getWidthTotalPixels(m: MountainData): number {
    return m.ws * SQUARE_SIZE + Math.round(m.wp * SQUARE_SIZE / 100);
}

function getHeightTotalPixels(m: MountainData): number {
    return m.hs * SQUARE_SIZE + Math.round(m.hp * SQUARE_SIZE / 100);
}

function vec3(x: number, y: number, z: number): Vec3 { return { x, y, z }; }

function lerpVec(a: Vec3, b: Vec3, t: number): Vec3 {
    return vec3(
        a.x + (b.x - a.x) * t,
        a.y + (b.y - a.y) * t,
        a.z + (b.z - a.z) * t,
    );
}

function dist(a: Vec3, b: Vec3): number {
    const dx = b.x - a.x, dy = b.y - a.y, dz = b.z - a.z;
    return Math.sqrt(dx * dx + dy * dy + dz * dz);
}

/**
 * Rotate a 3D point around a center on the Y axis by angleDeg degrees.
 * Angle is negated internally to convert from RPM's right-handed convention
 * to Babylon.js's left-handed convention.
 */
function rotateY(px: number, py: number, pz: number,
    cx: number, cz: number, angleDeg: number): [number, number, number] {
    const rad = -angleDeg * Math.PI / 180; // negate for LH
    const cos = Math.cos(rad);
    const sin = Math.sin(rad);
    const dx = px - cx;
    const dz = pz - cz;
    return [cx + dx * cos - dz * sin, py, cz + dx * sin + dz * cos];
}

function pickXKind(left: boolean, right: boolean): number {
    if (!left && right) return X_LEFT_OFFSET;
    if (left && right) return X_MID_OFFSET;
    if (left && !right) return X_RIGHT_OFFSET;
    return X_MIX_OFFSET;
}

/**
 * Accumulates mountain quads into flat arrays, then produces Babylon VertexData.
 *
 * texWidth/texHeight = dimensions of the generated 4×4 atlas (e.g. 64×64).
 */
export class MountainGeometryBuilder {
    private vertices: number[] = [];
    private indices: number[] = [];
    private uvs: number[] = [];
    private quadCount = 0;

    addMountain(
        tileX: number, tileY: number, tileZ: number,
        mountain: MountainData,
        texWidth: number, texHeight: number
    ): void {
        if (mountain.inverted) {
            this.addInvertedMountain(tileX, tileY, tileZ, mountain, texWidth, texHeight);
            return;
        }

        const wp = getWidthTotalPixels(mountain);
        const hp = getHeightTotalPixels(mountain);
        const faceHeight = Math.sqrt(wp * wp + hp * hp);
        const w = SQUARE_SIZE / texWidth;

        const localX = tileX * SQUARE_SIZE;
        const localY = tileY * SQUARE_SIZE;
        const localZ = tileZ * SQUARE_SIZE;

        const cx = localX + SQUARE_SIZE / 2;
        const cy = localY + SQUARE_SIZE / 2;
        const cz = localZ + SQUARE_SIZE / 2;

        const xLeft = localX;
        const xRight = localX + SQUARE_SIZE;
        const yTop = localY + hp;
        const yBot = localY;
        const zFront = localZ + SQUARE_SIZE + wp;
        const zBack = zFront - wp;

        // Base vectors for slope geometry (matches RPM updateGeometry exactly)
        const vecFrontB = vec3(xLeft, yBot, zFront);
        const vecBackB = vec3(xLeft, yTop, zBack);
        const vecFrontA = vec3(xLeft - wp, yBot, zBack);
        const vecBackA = vec3(xLeft, yTop, zBack);

        // Draw faces for sides without neighbors
        if (!mountain.b) {
            this.drawEntireFaces(mountain.l, mountain.r, 0,
                cx, cy, cz, texWidth, texHeight, w, faceHeight, wp,
                xLeft, xRight, yTop, yBot, zFront, zBack, 0,
                vecFrontA, vecBackA, vecFrontB, vecBackB);
        }
        if (!mountain.t) {
            this.drawEntireFaces(mountain.r, mountain.l, 180,
                cx, cy, cz, texWidth, texHeight, w, faceHeight, wp,
                xLeft, xRight, yTop, yBot, zFront, zBack, 0,
                vecFrontA, vecBackA, vecFrontB, vecBackB);
        }
        if (!mountain.l) {
            this.drawEntireFaces(mountain.t, mountain.b, -90,
                cx, cy, cz, texWidth, texHeight, w, faceHeight, wp,
                xLeft, xRight, yTop, yBot, zFront, zBack, 0,
                vecFrontA, vecBackA, vecFrontB, vecBackB);
        }
        if (!mountain.r) {
            this.drawEntireFaces(mountain.b, mountain.t, 90,
                cx, cy, cz, texWidth, texHeight, w, faceHeight, wp,
                xLeft, xRight, yTop, yBot, zFront, zBack, 0,
                vecFrontA, vecBackA, vecFrontB, vecBackB);
        }
    }

    /**
     * Add an inverted mountain (pit). Simple inner-wall geometry:
     * Each exposed side gets a vertical quad from surface level (y=0) down
     * to the pit bottom (y=-hp), with an optional slope piece if border
     * width > 0 that connects the floor outside to the top of the inner wall.
     *
     * The slopes go INWARD from adjacent floor tiles, angling down to the
     * tile edge. This creates the appearance of an upside-down mountain.
     */
    private addInvertedMountain(
        tileX: number, tileY: number, tileZ: number,
        mountain: MountainData,
        texWidth: number, texHeight: number
    ): void {
        const wp = getWidthTotalPixels(mountain);
        const hp = getHeightTotalPixels(mountain);
        const s = SQUARE_SIZE;

        const x0 = tileX * s;          // left (west) edge
        const x1 = x0 + s;             // right (east) edge
        const z0 = tileZ * s;          // top (north) edge
        const z1 = z0 + s;             // bottom (south) edge
        const yS = tileY * s;          // surface level
        const yB = yS - hp;            // pit bottom

        const coefX = COEF_TEX / texWidth;
        const coefY = COEF_TEX / texHeight;

        // Per-face-endpoint trim flags. Each face has two ends (corners).
        // An endpoint is trimmed when a diagonal pit exists at that corner,
        // because the diagonal pit's perpendicular slope also extends into
        // the same space and the two slopes would overlap.
        //
        // The condition is simply: does the diagonal pit exist at this corner?
        // It does NOT require the other cardinal to be empty — even when one
        // cardinal IS a neighbor (suppressing that face), the exposed face's
        // endpoint still overlaps with the diagonal's slope.
        //
        // Example: 01 / 11 — pit(1,0) has b=true, l=false, bl=true.
        // West face is drawn (!l). Its south end overlaps with pit(0,1)'s
        // north slope. Trim the south end of the west face.

        // West face (!l): A=(x0-wp,yS,z0) B=(x0-wp,yS,z1) C=(x0,yB,z1) D=(x0,yB,z0)
        if (!mountain.l) {
            if (wp > 0) {
                const trimN = !!mountain.tl;  // north end: diagonal pit at NW
                const trimS = !!mountain.bl;  // south end: diagonal pit at SW
                if (trimN && trimS) {
                    // both ends trimmed — degenerate, skip
                } else if (trimS) {
                    // south end trimmed: remove B, keep triangle ACD
                    this.addPitTriangle(
                        x0 - wp, yS, z0,   // A
                        x0,      yB, z1,   // C
                        x0,      yB, z0,   // D
                        texWidth, texHeight, coefX, coefY);
                } else if (trimN) {
                    // north end trimmed: remove A, keep triangle BCD
                    this.addPitTriangle(
                        x0 - wp, yS, z1,   // B
                        x0,      yB, z1,   // C
                        x0,      yB, z0,   // D
                        texWidth, texHeight, coefX, coefY);
                } else {
                    this.addPitQuad(
                        x0 - wp, yS, z0,    x0 - wp, yS, z1,
                        x0,      yB, z1,    x0,      yB, z0,
                        texWidth, texHeight, coefX, coefY);
                }
            } else {
                this.addPitQuad(
                    x0, yS, z0,  x0, yS, z1,
                    x0, yB, z1,  x0, yB, z0,
                    texWidth, texHeight, coefX, coefY);
            }
        }

        // East face (!r): A=(x1+wp,yS,z1) B=(x1+wp,yS,z0) C=(x1,yB,z0) D=(x1,yB,z1)
        if (!mountain.r) {
            if (wp > 0) {
                const trimS = !!mountain.br;  // south end: diagonal at SE
                const trimN = !!mountain.tr;  // north end: diagonal at NE
                if (trimS && trimN) {
                    // degenerate
                } else if (trimS) {
                    // south end trimmed: remove A, keep triangle BCD
                    this.addPitTriangle(
                        x1 + wp, yS, z0,   // B
                        x1,      yB, z0,   // C
                        x1,      yB, z1,   // D
                        texWidth, texHeight, coefX, coefY);
                } else if (trimN) {
                    // north end trimmed: remove B, keep triangle ACD
                    this.addPitTriangle(
                        x1 + wp, yS, z1,   // A
                        x1,      yB, z0,   // C
                        x1,      yB, z1,   // D
                        texWidth, texHeight, coefX, coefY);
                } else {
                    this.addPitQuad(
                        x1 + wp, yS, z1,    x1 + wp, yS, z0,
                        x1,      yB, z0,    x1,      yB, z1,
                        texWidth, texHeight, coefX, coefY);
                }
            } else {
                this.addPitQuad(
                    x1, yS, z1,  x1, yS, z0,
                    x1, yB, z0,  x1, yB, z1,
                    texWidth, texHeight, coefX, coefY);
            }
        }

        // North face (!t): A=(x1,yS,z0-wp) B=(x0,yS,z0-wp) C=(x0,yB,z0) D=(x1,yB,z0)
        if (!mountain.t) {
            if (wp > 0) {
                const trimE = !!mountain.tr;  // east end: diagonal at NE
                const trimW = !!mountain.tl;  // west end: diagonal at NW
                if (trimE && trimW) {
                    // degenerate
                } else if (trimE) {
                    // east end trimmed: remove A, keep triangle BCD
                    this.addPitTriangle(
                        x0, yS, z0 - wp,   // B
                        x0, yB, z0,         // C
                        x1, yB, z0,         // D
                        texWidth, texHeight, coefX, coefY);
                } else if (trimW) {
                    // west end trimmed: remove B, keep triangle ACD
                    this.addPitTriangle(
                        x1, yS, z0 - wp,   // A
                        x0, yB, z0,         // C
                        x1, yB, z0,         // D
                        texWidth, texHeight, coefX, coefY);
                } else {
                    this.addPitQuad(
                        x1, yS, z0 - wp,    x0, yS, z0 - wp,
                        x0, yB, z0,          x1, yB, z0,
                        texWidth, texHeight, coefX, coefY);
                }
            } else {
                this.addPitQuad(
                    x1, yS, z0,  x0, yS, z0,
                    x0, yB, z0,  x1, yB, z0,
                    texWidth, texHeight, coefX, coefY);
            }
        }

        // South face (!b): A=(x0,yS,z1+wp) B=(x1,yS,z1+wp) C=(x1,yB,z1) D=(x0,yB,z1)
        if (!mountain.b) {
            if (wp > 0) {
                const trimW = !!mountain.bl;  // west end: diagonal at SW
                const trimE = !!mountain.br;  // east end: diagonal at SE
                if (trimW && trimE) {
                    // degenerate
                } else if (trimW) {
                    // west end trimmed: remove A, keep triangle BCD
                    this.addPitTriangle(
                        x1, yS, z1 + wp,   // B
                        x1, yB, z1,         // C
                        x0, yB, z1,         // D
                        texWidth, texHeight, coefX, coefY);
                } else if (trimE) {
                    // east end trimmed: remove B, keep triangle ACD
                    this.addPitTriangle(
                        x0, yS, z1 + wp,   // A
                        x1, yB, z1,         // C
                        x0, yB, z1,         // D
                        texWidth, texHeight, coefX, coefY);
                } else {
                    this.addPitQuad(
                        x0, yS, z1 + wp,    x1, yS, z1 + wp,
                        x1, yB, z1,         x0, yB, z1,
                        texWidth, texHeight, coefX, coefY);
                }
            } else {
                this.addPitQuad(
                    x0, yS, z1,  x1, yS, z1,
                    x1, yB, z1,  x0, yB, z1,
                    texWidth, texHeight, coefX, coefY);
            }
        }

        // Corner triangles — fill gaps between adjacent slope faces.
        // A corner triangle is drawn when at least one of the two adjacent
        // faces is exposed AND either both faces are exposed (convex corner)
        // or a diagonal pit exists at that corner (concave corner).
        // The vertex positions are the same for both convex and concave:
        //   (face1 slope tip at surface, face2 slope tip at surface, pit bottom corner)
        if (wp > 0) {
            const faceN = !mountain.t;
            const faceS = !mountain.b;
            const faceW = !mountain.l;
            const faceE = !mountain.r;

            // SE corner (x1, z1)
            if ((faceS && faceE) || ((faceS || faceE) && !!mountain.br)) {
                this.addPitTriangle(
                    x1,      yS, z1 + wp,   // south slope tip
                    x1 + wp, yS, z1,         // east slope tip
                    x1,      yB, z1,         // bottom corner
                    texWidth, texHeight, coefX, coefY);
            }
            // SW corner (x0, z1)
            if ((faceS && faceW) || ((faceS || faceW) && !!mountain.bl)) {
                this.addPitTriangle(
                    x0 - wp, yS, z1,         // west slope tip
                    x0,      yS, z1 + wp,    // south slope tip
                    x0,      yB, z1,         // bottom corner
                    texWidth, texHeight, coefX, coefY);
            }
            // NE corner (x1, z0)
            if ((faceN && faceE) || ((faceN || faceE) && !!mountain.tr)) {
                this.addPitTriangle(
                    x1 + wp, yS, z0,         // east slope tip
                    x1,      yS, z0 - wp,    // north slope tip
                    x1,      yB, z0,         // bottom corner
                    texWidth, texHeight, coefX, coefY);
            }
            // NW corner (x0, z0)
            if ((faceN && faceW) || ((faceN || faceW) && !!mountain.tl)) {
                this.addPitTriangle(
                    x0,      yS, z0 - wp,    // north slope tip
                    x0 - wp, yS, z0,         // west slope tip
                    x0,      yB, z0,         // bottom corner
                    texWidth, texHeight, coefX, coefY);
            }
        }
    }

    /**
     * Draw a single quad for an inverted mountain pit face.
     * 4 explicit vertices (A, B, C, D) in winding order.
     */
    private addPitQuad(
        ax: number, ay: number, az: number,
        bx: number, by: number, bz: number,
        cx: number, cy: number, cz: number,
        dx: number, dy: number, dz: number,
        texW: number, texH: number,
        coefX: number, coefY: number,
    ): void {
        const u = (X_MIX_OFFSET * SQUARE_SIZE) / texW + coefX;
        const v = (Y_MIX_OFFSET * SQUARE_SIZE) / texH + coefY;
        const uw = SQUARE_SIZE / texW - coefX * 2;
        const vh = SQUARE_SIZE / texH - coefY * 2;
        // Same UV tile as normal mountains, just flip V so grass border is at top (surface)
        const v0 = 1.0 - v;          // top of tile
        const v1 = 1.0 - (v + vh);   // bottom of tile

        const base = this.quadCount * 4;
        this.vertices.push(ax, ay, az, bx, by, bz, cx, cy, cz, dx, dy, dz);
        this.indices.push(base, base + 1, base + 2, base, base + 2, base + 3);
        // A,B are at surface (top of slope) → get v1 (bottom of texture = grass border)
        // C,D are at pit bottom → get v0 (top of texture)
        this.uvs.push(u, v1, u + uw, v1, u + uw, v0, u, v0);
        this.quadCount++;
    }

    /**
     * Draw a single triangle for an inverted mountain pit corner.
     * 3 explicit vertices in winding order.
     */
    private addPitTriangle(
        ax: number, ay: number, az: number,
        bx: number, by: number, bz: number,
        cx: number, cy: number, cz: number,
        texW: number, texH: number,
        coefX: number, coefY: number,
    ): void {
        const u = (X_MIX_OFFSET * SQUARE_SIZE) / texW + coefX;
        const v = (Y_MIX_OFFSET * SQUARE_SIZE) / texH + coefY;
        const uw = SQUARE_SIZE / texW - coefX * 2;
        const vh = SQUARE_SIZE / texH - coefY * 2;
        const v0 = 1.0 - v;
        const v1 = 1.0 - (v + vh);

        // Allocate a 4-vert slot (duplicate C) for consistent quadCount indexing
        const base = this.quadCount * 4;
        this.vertices.push(ax, ay, az, bx, by, bz, cx, cy, cz, cx, cy, cz);
        this.indices.push(base, base + 1, base + 2);
        // A,B at surface → v1 (grass border), C at pit bottom → v0
        this.uvs.push(u, v1, u + uw, v1, u + uw / 2, v0, u + uw / 2, v0);
        this.quadCount++;
    }

    /**
     * Draw all face sections for one side. Matches RPM drawEntireFaces exactly.
     * Each section calls drawSideCorner which draws a flat face + corner piece.
     */
    private drawEntireFaces(
        left: boolean, right: boolean, angle: number,
        cx: number, cy: number, cz: number,
        texW: number, texH: number, w: number, faceHeight: number, wp: number,
        xLeft: number, xRight: number, yTop: number, yBot: number,
        zFront: number, zBack: number, yOffset: number,
        vecFrontA: Vec3, vecBackA: Vec3, vecFrontB: Vec3, vecBackB: Vec3
    ): void {
        const xKind = pickXKind(left, right);
        const nbSteps = Math.ceil(faceHeight / SQUARE_SIZE);
        const vecCenterA = lerpVec(vecFrontA, vecBackA, 0.5);
        const vecCenterB = lerpVec(vecFrontB, vecBackB, 0.5);

        if (faceHeight === SQUARE_SIZE) {
            // 1 Mix sprite (matches RPM: faceHeight === SQUARE_SIZE)
            this.drawSideCorner(xKind, Y_MIX_OFFSET, angle, cx, cy, cz,
                texW, texH, w, faceHeight, wp, xLeft, xRight,
                vecBackA.x, vecBackB.x, vecFrontA.x, vecBackB.x,
                yTop, yBot, zFront, zBack,
                vecFrontA.z, vecFrontB.z, vecBackA.z, vecBackB.z,
                yOffset, 0, dist(vecFrontA, vecFrontB));
        } else if (faceHeight <= 2 * SQUARE_SIZE) {
            // 2 sprites: Bot + Top
            this.drawSideCorner(xKind, Y_BOT_OFFSET, angle, cx, cy, cz,
                texW, texH, w, Math.floor(faceHeight / 2), wp, xLeft, xRight,
                vecCenterA.x, vecCenterB.x, vecFrontA.x, vecFrontB.x,
                vecCenterB.y, yBot, zFront, vecCenterB.z,
                vecFrontA.z, vecFrontB.z, vecCenterA.z, vecCenterB.z,
                yOffset, dist(vecCenterA, vecCenterB), dist(vecFrontA, vecFrontB));

            this.drawSideCorner(xKind, Y_TOP_OFFSET, angle, cx, cy, cz,
                texW, texH, w, Math.ceil(faceHeight / 2), wp, xLeft, xRight,
                vecBackA.x, vecBackB.x, vecCenterA.x, vecCenterB.x,
                yTop, vecCenterB.y, vecCenterB.z, zBack,
                vecCenterA.z, vecCenterB.z, vecBackA.z, vecBackB.z,
                yOffset, 0, dist(vecCenterA, vecCenterB));
        } else {
            // 3+ sprites: Bot + Mid(s) + Top
            const stepFrac = 1 / nbSteps;
            let vecStepLeftB = lerpVec(vecFrontA, vecBackA, stepFrac);
            let vecStepRightB = lerpVec(vecFrontB, vecBackB, stepFrac);

            // Bottom
            this.drawSideCorner(xKind, Y_BOT_OFFSET, angle, cx, cy, cz,
                texW, texH, w, Math.floor(faceHeight / nbSteps), wp, xLeft, xRight,
                vecStepLeftB.x, vecStepRightB.x, vecFrontA.x, vecFrontB.x,
                vecStepRightB.y, yBot, zFront, vecStepRightB.z,
                vecFrontA.z, vecFrontB.z, vecStepLeftB.z, vecStepRightB.z,
                yOffset, dist(vecStepLeftB, vecStepRightB), dist(vecFrontA, vecFrontB));

            // Middle segments
            for (let i = 2; i <= nbSteps - 1; i++) {
                const vecStepLeftA = vecStepLeftB;
                const vecStepRightA = vecStepRightB;
                vecStepLeftB = lerpVec(vecFrontA, vecBackA, i * stepFrac);
                vecStepRightB = lerpVec(vecFrontB, vecBackB, i * stepFrac);
                this.drawSideCorner(xKind, Y_MID_OFFSET, angle, cx, cy, cz,
                    texW, texH, w, Math.floor(faceHeight / nbSteps), wp, xLeft, xRight,
                    vecStepLeftB.x, vecStepRightB.x, vecStepLeftA.x, vecStepRightA.x,
                    vecStepRightB.y, vecStepRightA.y, vecStepRightA.z, vecStepRightB.z,
                    vecStepLeftA.z, vecStepRightA.z, vecStepLeftB.z, vecStepRightB.z,
                    yOffset, dist(vecStepLeftB, vecStepRightB), dist(vecStepLeftA, vecStepRightA));
            }

            // Top
            this.drawSideCorner(xKind, Y_TOP_OFFSET, angle, cx, cy, cz,
                texW, texH, w, Math.ceil(faceHeight / nbSteps), wp, xLeft, xRight,
                vecBackA.x, vecBackB.x, vecStepLeftB.x, vecStepRightB.x,
                yTop, vecStepRightB.y, vecStepRightB.z, zBack,
                vecStepLeftB.z, vecStepRightB.z, vecBackA.z, vecBackB.z,
                yOffset, 0, dist(vecStepLeftB, vecStepRightB));
        }
    }

    /**
     * Draw the side + corner for one section. Matches RPM drawSideCorner.
     * Always draws the flat vertical face; draws the sloped corner piece only
     * if border width (wp) > 0.
     */
    private drawSideCorner(
        xKind: number, yKind: number, angle: number,
        cx: number, cy: number, cz: number,
        texW: number, texH: number, w: number, faceHeight: number,
        wp: number, xLeft: number, xRight: number,
        xLeftTop: number, xRightTop: number, xLeftBot: number, xRightBot: number,
        yTop: number, yBot: number, zFront: number, zBack: number,
        zFrontLeft: number, zFrontRight: number, zBackLeft: number, zBackRight: number,
        yOffset: number, xCornerOffsetTop: number, xCornerOffsetBot: number
    ): void {
        // Flat vertical face (always drawn)
        this.drawFace(xKind, yKind, angle, cx, cz,
            texW, texH, w, faceHeight,
            xLeft, xRight, xLeft, xRight,
            yTop, yBot, zFront, zFront, zBack, zBack,
            yOffset, 0, 0, false);

        // Sloped corner piece (only if border width > 0)
        // Tiny Y offset prevents z-fighting when diagonal mountains' corner triangles overlap
        if (wp > 0) {
            this.drawFace(xKind, yKind, angle, cx, cz,
                texW, texH, w, faceHeight,
                xLeftTop, xRightTop, xLeftBot, xRightBot,
                yTop + 0.05, yBot + 0.05, zFrontLeft, zFrontRight, zBackLeft, zBackRight,
                yOffset, xCornerOffsetTop, xCornerOffsetBot, true);
        }
    }

    /**
     * Draw a single face quad. Matches RPM Mountain.drawFace exactly.
     * Handles both flat faces (isCorner=false) and corner/slope faces (isCorner=true).
     */
    private drawFace(
        xKind: number, yKind: number, angle: number,
        cx: number, cz: number,
        texW: number, texH: number, w: number, faceHeight: number,
        xLeftTop: number, xRightTop: number, xLeftBot: number, xRightBot: number,
        yTop: number, yBot: number,
        zFrontLeft: number, zFrontRight: number, zBackLeft: number, zBackRight: number,
        yOffset: number, xCornerOffsetTop: number, xCornerOffsetBot: number,
        isCorner: boolean
    ): void {
        // UV coordinates matching RPM Mountain.drawFace
        const coefX = COEF_TEX / texW;
        const coefY = COEF_TEX / texH;
        let x = (xKind * SQUARE_SIZE) / texW;
        let y = ((yKind * SQUARE_SIZE) + (yKind === Y_BOT_OFFSET ?
            SQUARE_SIZE - faceHeight : 0) + yOffset) / texH;
        let h = faceHeight / texH;
        x += coefX;
        y += coefY;
        w -= coefX * 2;
        h -= coefY * 2;

        // Compute UVs — different for corner vs flat face
        let uA: number, vA: number, uB: number, vB: number;
        let uC: number, vC: number, uD: number, vD: number;
        // Clamp corner offsets to SQUARE_SIZE to prevent negative UVs
        const clampTop = Math.min(xCornerOffsetTop, SQUARE_SIZE);
        const clampBot = Math.min(xCornerOffsetBot, SQUARE_SIZE);
        if (isCorner) {
            uA = ((xKind * SQUARE_SIZE) + ((SQUARE_SIZE - clampTop) / 2)) / texW + coefX;
            vA = y;
            uB = (((xKind + 1) * SQUARE_SIZE) - ((SQUARE_SIZE - clampTop) / 2)) / texW - coefX;
            vB = y;
            uC = (((xKind + 1) * SQUARE_SIZE) - ((SQUARE_SIZE - clampBot) / 2)) / texW - coefX;
            vC = y + h;
            uD = ((xKind * SQUARE_SIZE) + ((SQUARE_SIZE - clampBot) / 2)) / texW + coefX;
            vD = y + h;
        } else {
            uA = x;       vA = y;
            uB = x + w;   vB = y;
            uC = x + w;   vC = y + h;
            uD = x;       vD = y + h;
        }

        // Invert V for Babylon.js invertY texture loading
        vA = 1.0 - vA;
        vB = 1.0 - vB;
        vC = 1.0 - vC;
        vD = 1.0 - vD;

        // Vertices (RPM winding: A=topLeft, B=topRight, C=botRight, D=botLeft)
        let ax = xLeftTop, ay = yTop, az = zBackLeft;
        let bx = xRightTop, by = yTop, bz = zBackRight;
        let cxx = xRightBot, cyy = yBot, czz = zFrontRight;
        let dx = xLeftBot, dy = yBot, dz = zFrontLeft;

        // Rotate around center (negate angle for LH coordinate system)
        if (angle !== 0) {
            [ax, ay, az] = rotateY(ax, ay, az, cx, cz, angle);
            [bx, by, bz] = rotateY(bx, by, bz, cx, cz, angle);
            [cxx, cyy, czz] = rotateY(cxx, cyy, czz, cx, cz, angle);
            [dx, dy, dz] = rotateY(dx, dy, dz, cx, cz, angle);
        }

        const base = this.quadCount * 4;
        this.vertices.push(
            ax, ay, az,
            bx, by, bz,
            cxx, cyy, czz,
            dx, dy, dz
        );
        this.indices.push(base, base + 1, base + 2, base, base + 2, base + 3);
        this.uvs.push(
            uA, vA,
            uB, vB,
            uC, vC,
            uD, vD
        );
        this.quadCount++;
    }

    build(): VertexData | null {
        if (this.quadCount === 0) return null;

        const vertexData = new VertexData();
        vertexData.positions = new Float32Array(this.vertices);
        vertexData.indices = new Uint32Array(this.indices);
        vertexData.uvs = new Float32Array(this.uvs);

        const normals: number[] = [];
        VertexData.ComputeNormals(vertexData.positions, vertexData.indices, normals);
        vertexData.normals = new Float32Array(normals);

        return vertexData;
    }

    clear(): void {
        this.vertices = [];
        this.indices = [];
        this.uvs = [];
        this.quadCount = 0;
    }
}
